name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-exam-part2:latest

      # Test the Docker image
      - name: Test Docker image
        run: |
          docker run --name devops-final-exam-part2-container -d -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-exam-part2:latest
          # Wait for the container to be up and running
          sleep 10
          # Test if the app is running by making a request
          curl --fail http://localhost:5000 || (docker logs devops-final-exam-part2-container && exit 1)
          docker stop devops-final-exam-part2-container

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-exam-part2:latest
